### ISSUE TITLE
Linux: Quirky scrolling in mod browser

### ISSUE THREAD

**Issue by Teklad** [tModLoader/tModLoader#203]
When using Mod Browser in Linux (May apply to Windows too.... haven't tested), the scrolling seems to be really odd.  If I use my mouse wheel to scroll right after the list has loaded, it will scroll literally almost to the bottom of the mod list.  In order to fix this behavior I have to resize the Terraria window once or twice, after which the behavior will revert back to normal scrolling.

My only guess is it somehow isn't getting the correct sizes for the window whenever the list is loaded, but I've not looked at the source extensively so its hard to be sure.

**Comment by Cheezegami** [comment]
Can confirm this on windows as well, might be because I have a 144hz monitor.

**Comment by Teklad** [comment]
@Cheezegami I use a 60Hz monitor so I don't think that's the issue here.  One thing that's extremely consistent though is the behavior changes every time I adjust the window size.  After adjusting it a few times it will start behaving for a little bit... until I exit/re-enter the mod browser, resize the window again, or install a mod.

**Comment by zauberparacelsus** [comment]
I have this issue as well.  After resizing the terraria window once or twice, it isn't always fixed, and sometimes changes to not scrolling at all.

**Comment by abluescarab** [comment]
It also happens in the mod list on the main menu. If I scroll down, it scrolls normally until I hit the bottom of the list; then when I try to scroll back up, it jumps too far.

**Comment by Jofairden** [comment]
Experienced this myself a few times, have been unable to find the exact cause. I can try a few things that'll maybe fix it

**Comment by damian181297** [comment]
its because frame skip is on after i turned it off it fixed it for me (on windows 10) dont know about linux.

**Comment by Kenahh1** [comment]
It is not a Tmodloader problem, it is a Terraria problem because it happens while scrolling in the achievements page.

To fix it you need to go to the video options then resolution to set it to the maximum recommended resolution for your monitor, then enable borderless window.

**Comment by IdrisQe** [comment]
Also necroing this, I'm afraid, to state the above fixes don't always work. Another cause of this problem seems to be using Subtle frameskip. It may have to do with refresh rates, possibly, although I've not been able to test that thoroughly. But the point is **Subtle frameskip can be another culprit of this, at times.**

**Setting frameskip to off (which comes with all sorts of other problems on a 120/144hz monitor) or setting it to on (which limits you to 53 FPS but hey it's better than nothing) seem to fix the problem for me.** I've run at 1366x768 borderless windowed on a 60hz monitor, 1920x1080 borderless windowed on a 120/144hz monitor (I'm afraid I forget which), and 1366x768 fullscreen on a 1600x900 monitor (which looks awful but that computer was too weak for that monitor) and I'm pretty sure I've experienced this problem on each, in both vanilla and tModloader.

_(Honestly I wish instead of this frameskip nonsense they just had a slider for FPS Cap between 30 and 60, or off for those who want to live dangerously in the flickery, speedy zone of higher-than-intended FPS, but that's beside the point.)_

**Comment by chatrat12** [comment]
This is caused because `UserInterface.Update` is called way more times than `PlayeInput.Update`

![image](https://user-images.githubusercontent.com/251682/52019235-2a611300-24bb-11e9-983d-2e0de6fd5c9e.png)

I was able to fix this in my mod by only while in game go doing this.

```cs
public override void UpdateUI(GameTime gameTime)
{ 
    _interface.Update(gameTime);
    PlayerInput.ScrollWheelDeltaForUI = 0;
}
```

I believe 0.11 beta has a hook for PostUpdateEverything. If the ScrollWheelDeltaForUI was reset there, it may also fix the issues in the main menu :D I know this is probably a vanilla bug, but we could patch in a fix :D

**Comment by JavidPack** [comment]
Each UserInterface should only call Update once. Are you sure all those Updates are the same instance of a UserInterface? If they are different, then that is expected and each UserInterface will have an opportunity to use the value of ScrollWheelDeltaForUI. If you could post your enabled.json and show the code generating that output, it would be helpful.

**Comment by JavidPack** [comment]
Hm, that pattern should only be possible if the window isn't focused or if the spash screen is showing. Are you sure you are looking at logs from when you were on the main menu itself and the window was focused?

DoUpdate_HandleInput is called in Main.DoUpdate just like the interface updates.

**Comment by chatrat12** [comment]
Can confirm window was focused and was scrolling through the mod browser. What I posted above is the behavior I get when focused and in the menu. Quite strange.

**Comment by chatrat12** [comment]
Found it!

```cs
if (Main.FrameSkipMode == 0 || Main.FrameSkipMode == 2)
{
	Main.UpdateTimeAccumulator += gameTime.ElapsedGameTime.TotalSeconds;
	if (Main.UpdateTimeAccumulator < 0.016666666666666666 && !Main.superFast)
	{
		if (Main.FrameSkipMode == 2)
		{
			Main.instance.SuppressDraw();
		}
		Console.WriteLine("Not so fast mister.");
		return;
	}
```
Interface update happens BEFORE frame skipping and input update happens AFTER frame skipping.

**Comment by Jofairden** [comment]
@JavidPack have we fixed this yet? I can't seem to reproduce it anymore.

**Comment by JavidPack** [comment]
Haven't yet. Someone recently told me you need to be on frameskip subtle as well. You probably can't reproduce it since you are hitting 60 fps.

**Comment by JavidPack** [comment]
Thanks @chatrat12 , kinda forgot about this issue. 

My fix simply fixes the scroll. I still don't quite get what the game is doing. Every 4 or so times that I focus back to the game, I noticed dozens of frameskips being logged as I assume it was catching up. I don't know why it wouldn't happen consistently, but when it was happening, for those few seconds the scrolling was very abrupt because of UIUpdate running dozens of times and input update not happening.

I'm worried other issues might be lurking related to this, but it's not making too much sense to me right now. At least the scroll should be fixed.

**Comment by chatrat12** [comment]
Glad to hear. I wouldn't be surprised if other issues were lurking. Frankly, Terraria's stab at variable frame rate is... not the greatest :D
