### ISSUE TITLE
Shield of Cthulhu doesnt work properly with CanHitNPC() hooks

### ISSUE THREAD

**Issue by SheepishShepherd** [tModLoader/tModLoader#389]
### Description

The Shield of Cthulhu appears to be when applied to CanHitNPC hooks. I have tested it in ModPlayer, GlobalItem and GlobalNPC classes, and all produce the same result.

### Steps to Reproduce

1.) Add CanHitNPC hooks to any or all of the above classes (In my case I tried all three and made it return false if the target was a Bunny)
2.) Load into a world with the Shield of Cthulhu equipped
3.) Dash into a bunny to see if it works, and the first time it does
4.) Dash into the same bunny again and watch it die

### Expected behavior 

Shield of Cthulhu will not hit ANY npcs while the CanHitNPC hooks are false

### Actual behavior

Shield of Cthulhu will not hit an npc ONCE, and then always hit npcs until you load up the world again.

### Reproduction frequency

Happens every time with all CanHitNPC hooks from each class

### Versions

v0.10.1.5

### Mods

No mods needed to reproduce

### Additional Information

For some reason it works 100% properly with modded npcs. I have tested the hooks on my own npcs and the shield of cthulhu never hits them, but will hit normal npcs afterwards.

**Comment by JavidPack** [comment]
Turns out the 1st hit not working is probably a vanilla bug. I just reproduced that on 1.3.5.3.

**Comment by Chicken-Bones** [comment]
We'd need a more general hook for preventing NPC damage, awaiting feedback

**Comment by Solxanich** [comment]
Flagged as Fixed in #1231

**Comment by JavidPack** [comment]
Just tested, not happening anymore. The unusual missing of the 1st attack is still happening, but now all subsequent dashes result in the player colliding and bouncing off but not doing any damage. Not sure if bouncing off should still occur, but that can be another discussion later if it comes up.
