### ISSUE TITLE
OutOfMemory should crash to desktop

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#660]
Sometimes an OutOfMemory exception happens and we catch the exception. It has been suggested that when this particular exception happens that we crash to desktop and show a messagebox explaining how to avoid OutOfMemory exceptions. The idea is that the exception is pretty much unrecoverable from, and catching it might put the game in a weird state.

**Comment by Chicken-Bones** [comment]
This error is actually an event stack overflow. The first chance exception handler needs to be wrapped in a try catch and a thread local reentrant check

**Comment by Chicken-Bones** [comment]
Fixed https://github.com/tModLoader/tModLoader/commit/527cff941c0de82034b15c6bc4f23405d3a7759b

**Comment by Mirsario** [comment]
OOMs still don't crash the game in 0.11.5.

![image](https://user-images.githubusercontent.com/6795251/68673921-e6309200-0565-11ea-9e63-f05577efd7a5.png)
![image](https://user-images.githubusercontent.com/6795251/68673931-ea5caf80-0565-11ea-85b9-22d23883981e.png)

**Comment by Mirsario** [comment]
Reopened with #713 .
