### ISSUE TITLE
Big mods wont download

### ISSUE THREAD

**Issue by POGchamp1234567890** [tModLoader/tModLoader#921]
This happens when ever I try to download large mod packs like calamity and thorium in just wondering what I can do.

**Comment by Jofairden** [comment]
Try downloading them from here: http://mirror.sgkoi.dev/
Let us know if that works

**Comment by QuoteMasterN** [comment]
I'm having a similar issue on Ubuntu 20.04. Downloading from the mirror does work. So far the mods I've attempted to download that don't work are Thorium, Calamity (Both the base mod and the music), Overhaul, and other mods that add a lot of content. My computer can download from the mirror.

**Comment by Shockah** [comment]
Apparently it should be noted it's a Mac/Linux Mono issue.

Source:
![image](https://user-images.githubusercontent.com/718172/84060322-4d0f1000-a9bc-11ea-8e67-4a23bbe2a97f.png)
https://discordapp.com/channels/103110554649894912/436261997416546305/719599957140701284

**Comment by Jofairden** [comment]
I think we had these issues before, I wish I had a mac or linux so I could reproduce.

**Comment by Redd56** [comment]
still reproducing

**Comment by NickVolynkin** [comment]
Hi! I can help with reproducing it on macOS.

**Comment by JulianGmp** [comment]
Reproducing this issue on Linux, I am unable to download any mods through the mod browser.
I was able to download the mods manually from http://mirror.sgkoi.dev/ and move them into my mods directory, so that's a valid work around for now.

Are there any logs that I could share which could be of help?

**Comment by Redst0neFlux** [comment]
Reproduced on ubuntu
was able to download mods like recipe browser and antiaris, but not calamity or thorium

**Comment by Hotmud9** [comment]
Reproduced on the latest Mac version.

**Comment by e3pax** [comment]
Reproduced on Arch Linux.

**Comment by Mirsario** [comment]
We've fixed this in 1.4 by unifying Windows and Unix versions of the game under a single runtime that is ensured to be stable. That cannot be backported, so use web mirrors until 1.4 is ready.

**Comment by Steviegt6** [comment]
> > We've fixed this in 1.4 by unifying Windows and Unix versions of the game under a single runtime that is ensured to be stable. That cannot be backported, so use web mirrors until 1.4 is ready.
> 
> Might want to close this issue then, if that is the case.

It's still an issue in 1.3, which is what a majority of players use. Someone could always come along and potentially figure out a fix, too.

**Comment by ExistingExpert** [comment]
**I have the fix for 1.3.**
I downloaded the `mono` package (in Garuda Linux Barebones, an Arch-based distro), then I went to Tmodloader's local files, by hitting browse local files from steam, and executed the `tmodloader-mono` shell script. Tested by downloading Thorium, it downloaded with no issues.

**Comment by r0ar** [comment]
> I have the fix for 1.3.
> I downloaded the mono package (in Garuda Linux Barebones, an Arch-based distro), then I went to Tmodloader's local files, by hitting browse local files from steam, and executed the tmodloader-mono shell script. Tested by downloading Thorium, it downloaded with no issues.

Installing mono package alone on Arch Linux fixed the issue for me (Thanks!). I don't need to execute the shell script. Just running it from Steam works.

**Comment by wolfw3** [comment]
From what it appears this fix only works directly on Steam if you are running steam native, not steam runtime. (Running tmodloader-mono directly still works regardless)

**Comment by Mirsario** [comment]
This issue should now be fixed within 1.4 TML, as Mono has been replaced with .NET 5, and mod browser code is now quite different with the addition of steam workshop support. An alpha version of 1.4 TML can be found in [our discord](https://discord.gg/RMZCqq6).

Meanwhile, for 1.3:
> Use manual downloads from http://javid.ddns.net/tModLoader/DirectModDownloadListing.php

**Comment by Delanii** [comment]
> From what it appears this fix only works directly on Steam if you are running steam native, not steam runtime. (Running tmodloader-mono directly still works regardless)

I would like to also pinch in, eventhough it is closed. Even though I am running steam native on Manjaro Linux (Arch derivative) and installed `mono` packages mentioned here, I was still unable to download "big mods" (Calamity for example). Only reliable way to download mods on Linux for me was to use the script `tmodloader-mono`.

Thank you, that really helped!

Even though this should be fixed in 1.4, I think it would be great to leave this script, and any its dependencies in tmodloader to have it as a fallback in case the 1.4 fix will not work. Seems to me that it proved reliable workaround, with little effort (if mentioned in readme what to do).

Thanks for the software, now I go play Terrraria with some mods ;)

**Comment by Redd56** [comment]
still having issues, now mono script no longer works. just yells [https://pastebin.com/WHKqsTFR](url)

**Comment by ExistingExpert** [comment]
> still having issues, now mono script no longer works. just yells [https://pastebin.com/WHKqsTFR](url)

You are running on linux, but why is the executable `tmodloader.exe`

**Comment by Redd56** [comment]
> > still having issues, now mono script no longer works. just yells [https://pastebin.com/WHKqsTFR](url)
> 
> You are running on linux, but why is the executable `tmodloader.exe`

i was using the workaround described above, which was to use the tmodloader-mono script, which uses mono runtime  to run the windows version of tmodloader
